global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: sdn-primary
    static_configs:
      - targets: ["ryu-primary:5000"]
  - job_name: sdn-backup
    static_configs:
      - targets: ["ryu-backup:5000"]
